### ISSUE TITLE
Multiple Masks @,#

### ISSUE THREAD

**Issue by jensneuse** [bitjjj/SocialTokenAutoComplete#1]
Hey,  very nice lib!
What if I'd like to scan not only for persons but also for #hashtags and supply another array for these?

**Comment by bitjjj** [comment]
Sorry, this lib can only check '@' character at present.

**Comment by jensneuse** [comment]
I managed to implement it myself. I`m now able to add as many tokens as i like. Every token adds his own array of <whatever object> which can be updated at runtime. You can even use " " as token which is the common facebook behavior. I will upload it when I find time to clean the code..

**Comment by bitjjj** [comment]
Great! Thank you very much. You can publish it as your own
